version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.1
  - dependency-name: honeybadger
    versions:
    - 4.7.2
    - 4.7.3
  - dependency-name: pry
    versions:
    - 0.13.1
    - 0.14.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: invisible_captcha
    versions:
    - 1.1.0
